print('HELLO')
naam = input('Wat is uw naam?')
print (naam)
adres = input('Wat is uw adres?')
print (adres)
postcode = input('Wat is uw postcode?')
print(postcode)
woonplaats = input('Wat is uw woonplaats?')
print(woonplaats)

print(f'--------------------------------')
print("naam: " + naam)
print("adres:" + adres)
print("postcode: " + postcode)
print("woonplaats: " + postcode)
print(f'----------------------------------')